using System;
using System.Collections.Generic;

#nullable disable

namespace DataMigration.Data.SourceDBModels
{
    public partial class TestPscdwj1
    {
        public string Emplid { get; set; }
        public string FirstName { get; set; }
        public string NamePrefix { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PrefFirstName { get; set; }
        public string CdwOffiAreaCode { get; set; }
        public string CdwOffiPhone { get; set; }
        public string EmailAddr { get; set; }
        public string NextReviewDt { get; set; }
        public string HireDt { get; set; }
        public string TerminationDt { get; set; }
        public string SupervisorId { get; set; }
        public string Title { get; set; }
        public string JobFamily { get; set; }
        public string Deptid { get; set; }
        public string Jobcode { get; set; }
        public string FullPartTime { get; set; }
        public string EmplType { get; set; }
        public string JobEffdt { get; set; }
        public string EmplStatus { get; set; }
        public string Company { get; set; }
        public string Extension { get; set; }
        public string CdwPgrAreaCode { get; set; }
        public string CdwPgrPhone { get; set; }
        public string CdwVacHrsEarned { get; set; }
        public string CdwVacHrsTaken { get; set; }
        public string CdwSikHrsEarned { get; set; }
        public string CdwSickHrsTaken { get; set; }
        public string CdwFltHrsEarned { get; set; }
        public string CdwFltHrsTaken { get; set; }
        public string Location { get; set; }
        public string Descrshort { get; set; }
        public string CdwStartTime { get; set; }
        public string CdwEndTime { get; set; }
        public string StdHours { get; set; }
        public string ManagerLevel { get; set; }
        public string CdwCellPhone { get; set; }
        public string CdwBbPhone { get; set; }
        public string CdwBcelPhone { get; set; }
        public string CdwPcellPhone { get; set; }
        public string PositionNbr { get; set; }
        public string PerOrg { get; set; }
        public string CdwVendorName { get; set; }
        public string TreeNode { get; set; }
        public string Node1 { get; set; }
        public string Node2 { get; set; }
        public string DeptDescr { get; set; }
        public string JobcodeDescr { get; set; }
        public string LocationDescr { get; set; }
        public string SupervisorName { get; set; }
        public string CdwMgrLvlDesc { get; set; }
        public string RegRegion { get; set; }
        public string ReportsTo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CdwHomeAreaCode { get; set; }
        public string CdwHomePhone { get; set; }
        public string MarStatus { get; set; }
        public string Birthdate { get; set; }
        public string Sex { get; set; }
        public string EthnicGroup { get; set; }
        public string NationalId { get; set; }
        public string ParentNodeName { get; set; }
        public string Action { get; set; }
        public string ActionDt { get; set; }
        public string ActionReason { get; set; }
        public string LastHireDt { get; set; }
        public string TaxLocationCd { get; set; }
        public string JobEntryDt { get; set; }
        public string DeptEntryDt { get; set; }
        public string Shift { get; set; }
        public string RegTemp { get; set; }
        public string Paygroup { get; set; }
        public string HolidaySchedule { get; set; }
        public string BusinessUnit { get; set; }
        public string FlsaStatus { get; set; }
        public string EntryDate { get; set; }
        public string Fte { get; set; }
        public string Estabid { get; set; }
        public string HrStatus { get; set; }
        public string CdwPcnEffdt { get; set; }
        public string CdwBonusType { get; set; }
        public string SeniorityPayDt { get; set; }
        public string CmpnySeniorityDt { get; set; }
        public string ServiceDt { get; set; }
        public string Name { get; set; }
        public string NameDisplay { get; set; }
        public string EthnicGrpCd { get; set; }
        public string CdwEthGrpDescr { get; set; }
        public string CdwJobcodeEffdt { get; set; }
        public string CdwDeptEffdt { get; set; }
        public string CdwLocationEffdt { get; set; }
        public string WorkersCompCd { get; set; }
        public string Eeo1code { get; set; }
        public string EeoJobGroup { get; set; }
        public string LastDateWorked { get; set; }
        public string JobIndicator { get; set; }
        public string CdwItDeptFlg { get; set; }
        public string Smoker { get; set; }
        public string DescrPosition { get; set; }
        public string CdwJobEntryDt { get; set; }
        public string PositionEntryDt { get; set; }
        public string CdwLoadType { get; set; }
        public string Exclude { get; set; }
        public string ContractEmplid { get; set; }
        public string Oprid { get; set; }
        public string CdwPersona { get; set; }
        public string CdwAs400Oprid { get; set; }
        public DateTime? LosstartDate { get; set; }
        public DateTime? HireDate { get; set; }
        public int? Losmonth { get; set; }
        public string LosgroupDescription { get; set; }
        public int? LosgroupCode { get; set; }
        public string CoworkerCode { get; set; }
        public string DirectPhone { get; set; }
        public string CompanyCode { get; set; }
        public string CdwneighborhoodLocationCode { get; set; }
        public int? PeopleSoftCoWorkerFlag { get; set; }
        public int? CoworkerPositionCode { get; set; }
        public DateTime? TerminationDate { get; set; }
        public string UnionCoworkerCode { get; set; }
        public long? Countthrowaway { get; set; }
    }
}
